[package]
name = "vara-ticket-app"
version = "0.1.0"
edition = "2021"

[dependencies]
parity-scale-codec = { version = "3.6.12", default-features = false }
scale-info = { version = "2.11.6", default-features = false }
sails-rs = "0.7.1"
